pr: none

trigger:
- master

jobs:

- job: PublishToBintray
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      set -ev
      curl -O -L --retry 3 https://github.com/sormuras/bach/raw/master/install-jdk.sh
      source install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu8.38.0.13-ca-jdk8.0.212-linux_x64.tar.gz
      ./mvnw verify -DskipTests
      cd build/com.liferay.ide-repository
      ./deployToBintray.sh
    displayName: Build
    env:
      BINTRAY_USER: $(BINTRAY_USER)
      BINTRAY_API_KEY: $(BINTRAY_API_KEY)